"""Unit tests for scripts/generate-homepage-services.py.

Every path is a temporary file: the script's .env, template and output
constants are pointed at tmp_path, so nothing under configs/ is read or
written.
"""

import sys

import pytest
import yaml

pytestmark = pytest.mark.unit


@pytest.fixture
def homepage(load_script, tmp_path, monkeypatch):
    module = load_script("generate-homepage-services.py")
    monkeypatch.setattr(module, "ENV_FILE", tmp_path / ".env")
    monkeypatch.setattr(module, "TEMPLATE_FILE", tmp_path / "services.yaml.template")
    monkeypatch.setattr(module, "OUTPUT_FILE", tmp_path / "services.yaml")
    return module


TEMPLATE = """\
- Media:
    - Sonarr:
        href: http://${GLUETUN_IP}:8989/
    - Radarr:
        href: /radarr/
- Downloads:
    - qBittorrent:
        href: /qbittorrent/
- Extras:
    - Unmapped:
        href: /unmapped/
"""


def test_refuses_to_run_without_pyyaml(load_script, monkeypatch, capsys):
    monkeypatch.setitem(sys.modules, "yaml", None)
    with pytest.raises(SystemExit) as exit_info:
        load_script("generate-homepage-services.py")
    assert exit_info.value.code == 1
    assert "PyYAML is required" in capsys.readouterr().err


def test_read_env_strips_quotes_and_trailing_comments(homepage, tmp_path):
    env = tmp_path / ".env"
    env.write_text(
        "# a comment line\n"
        "lowercase=ignored\n"
        'DOUBLE="quoted # kept"\n'
        "SINGLE='single'\n"
        'LONE="\n'
        "COMMENTED=value # note\n"
        "HASH=a#b\n"
        "EMPTY=\n"
    )
    assert homepage.read_env(env) == {
        "DOUBLE": "quoted # kept",
        "SINGLE": "single",
        "LONE": '"',
        "COMMENTED": "value",
        "HASH": "a#b",
        "EMPTY": "",
    }


def test_expand_substitutes_defined_variables(homepage):
    assert homepage.expand("http://${HOST}:${PORT}/", {"HOST": "h", "PORT": "1"}) == (
        "http://h:1/"
    )


def test_expand_refuses_an_undefined_variable(homepage):
    with pytest.raises(SystemExit) as exit_info:
        homepage.expand("${ZED} ${ALPHA} ${ZED} ${OK}", {"OK": "1"})
    assert "references ALPHA, ZED" in str(exit_info.value)


def test_read_profiles_reads_only_profile_lines(homepage, tmp_path):
    env = tmp_path / ".env"
    env.write_text(
        "SONARR_PROFILE=enabled\nRADARR_PROFILE=disabled\nOTHER=enabled\n"
        "LIDARR_PROFILE=enabled # comment\n"
    )
    assert homepage.read_profiles(env) == {
        "SONARR_PROFILE": True,
        "RADARR_PROFILE": False,
    }


def test_is_enabled(homepage):
    profiles = {"SONARR_PROFILE": True, "RADARR_PROFILE": False}
    assert homepage.is_enabled("Unmapped", profiles) is True
    assert homepage.is_enabled("Sonarr", profiles) is True
    assert homepage.is_enabled("Radarr", profiles) is False
    # Mapped but absent from .env: kept rather than silently hidden.
    assert homepage.is_enabled("Lidarr", profiles) is True


def test_main_skips_without_an_env_file(homepage, tmp_path, capsys):
    assert homepage.main() == 0
    assert "does not exist yet, skipping" in capsys.readouterr().err
    assert not (tmp_path / "services.yaml").exists()


def test_main_drops_disabled_apps_and_empty_sections(homepage, tmp_path):
    (tmp_path / ".env").write_text(
        "GLUETUN_IP=10.0.0.2\nSONARR_PROFILE=enabled\nRADARR_PROFILE=disabled\n"
        "QBITTORRENT_PROFILE=disabled\n"
    )
    (tmp_path / "services.yaml.template").write_text(TEMPLATE)
    assert homepage.main() == 0
    output = tmp_path / "services.yaml"
    text = output.read_text()
    assert text.startswith("# Generated by scripts/generate-homepage-services.py")
    assert yaml.safe_load(text) == [
        {"Media": [{"Sonarr": {"href": "http://10.0.0.2:8989/"}}]},
        {"Extras": [{"Unmapped": {"href": "/unmapped/"}}]},
    ]
    assert output.stat().st_mode & 0o777 == 0o644


def test_main_tolerates_a_chmod_it_is_not_allowed(homepage, tmp_path, monkeypatch):
    (tmp_path / ".env").write_text("GLUETUN_IP=10.0.0.2\n")
    (tmp_path / "services.yaml.template").write_text(TEMPLATE)

    def refuse(self, mode):
        raise PermissionError("not the owner")

    monkeypatch.setattr(homepage.Path, "chmod", refuse)
    assert homepage.main() == 0
    assert "qBittorrent" in (tmp_path / "services.yaml").read_text()
